# These are supported funding model platforms

github: [yourusername] # Replace with your GitHub username
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective name
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform name
community_bridge: # Replace with your Community Bridge name
liberapay: # Replace with your Liberapay username
issuehunt: # Replace with your IssueHunt username
otechie: # Replace with your Otechie username
custom: # Replace with your custom funding URL
