# Email Integration Configuration for REChain®️ VC Lab
# This configuration enables email notifications for GitHub events

name: Email Integration

# Email Service Configuration
email:
  # SMTP server configuration
  smtp:
    host: ${{ secrets.SMTP_HOST }}
    port: ${{ secrets.SMTP_PORT }}
    username: ${{ secrets.SMTP_USERNAME }}
    password: ${{ secrets.SMTP_PASSWORD }}
    tls: true
    ssl: false
    
  # Email addresses
  addresses:
    # From address
    from: "noreply@rechain.vc"
    
    # To addresses for different events
    to:
      general: "team@rechain.vc"
      security: "security@rechain.vc"
      releases: "releases@rechain.vc"
      failures: "dev-team@rechain.vc"
      
    # CC addresses
    cc:
      general: "managers@rechain.vc"
      
    # BCC addresses
    bcc:
      general: "archive@rechain.vc"

# Notification Settings
notifications:
  # Issue events
  issues:
    created: true
    closed: true
    assigned: true
    labeled: true
    commented: true
    
  # Pull request events
  pull_requests:
    opened: true
    closed: true
    merged: true
    reviewed: true
    commented: true
    
  # Release events
  releases:
    published: true
    prereleased: true
    
  # Workflow events
  workflows:
    success: false  # Usually don't email on success
    failure: true
    cancelled: false
    
  # Security events
  security:
    vulnerability: true
    dependency: true
    secret: true

# Email Templates
templates:
  subject_prefix: "[REChain VC Lab]"
  
  issue_created:
    subject: "{prefix} New Issue: {title}"
    body: |
      A new issue has been created in the {repository} repository.
      
      **Title**: {title}
      **URL**: {url}
      **Author**: {author}
      **Labels**: {labels}
      
      **Description**:
      {description}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  issue_closed:
    subject: "{prefix} Issue Closed: {title}"
    body: |
      An issue has been closed in the {repository} repository.
      
      **Title**: {title}
      **URL**: {url}
      **Closed by**: {closed_by}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  pr_opened:
    subject: "{prefix} New Pull Request: {title}"
    body: |
      A new pull request has been opened in the {repository} repository.
      
      **Title**: {title}
      **URL**: {url}
      **Author**: {author}
      **Base**: {base} ← **Head**: {head}
      
      **Description**:
      {description}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  pr_merged:
    subject: "{prefix} Pull Request Merged: {title}"
    body: |
      A pull request has been merged in the {repository} repository.
      
      **Title**: {title}
      **URL**: {url}
      **Merged by**: {merged_by}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  release_published:
    subject: "{prefix} New Release: {name}"
    body: |
      A new release has been published in the {repository} repository.
      
      **Name**: {name}
      **Tag**: {tag}
      **URL**: {url}
      **Author**: {author}
      
      **Release Notes**:
      {body}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  workflow_failure:
    subject: "{prefix} Workflow Failed: {workflow}"
    body: |
      A workflow has failed in the {repository} repository.
      
      **Workflow**: {workflow}
      **Branch**: {branch}
      **Commit**: {commit}
      **URL**: {url}
      
      **Error Details**:
      {error_details}
      
      ---
      This is an automated notification from REChain VC Lab.
      
  security_vulnerability:
    subject: "{prefix} Security Vulnerability Detected"
    body: |
      A security vulnerability has been detected in the {repository} repository.
      
      **Vulnerability**: {vulnerability}
      **Severity**: {severity}
      **Package**: {package}
      **Version**: {version}
      
      **Description**:
      {description}
      
      **Recommendation**:
      {recommendation}
      
      ---
      This is an automated notification from REChain VC Lab.

# Custom Fields
custom_fields:
  # Add custom fields for your organization
  project: "REChain VC Lab"
  team: "Development Team"
  environment: "Production"
  support_email: "support@rechain.vc"

# Filtering Rules
filters:
  # Only notify for specific branches
  branches:
    include: ["main", "develop", "release/*"]
    exclude: ["feature/*", "bugfix/*"]
    
  # Only notify for specific labels
  labels:
    include: ["bug", "feature", "security", "release"]
    exclude: ["documentation", "chore"]
    
  # Only notify for specific repositories
  repositories:
    include: ["rechain-vc-lab", "rechain-*"]
    exclude: ["test-*", "temp-*"]

# Rate Limiting
rate_limiting:
  # Maximum emails per hour
  max_per_hour: 20
  
  # Cooldown period between emails
  cooldown_seconds: 300
  
  # Batch similar notifications
  batch_similar: true
  
  # Digest mode (send summary emails)
  digest_mode: true
  digest_interval: "daily"

# Error Handling
error_handling:
  # Retry failed emails
  retry_attempts: 3
  
  # Retry delay in seconds
  retry_delay: 300
  
  # Log errors to GitHub Actions
  log_errors: true
  
  # Fallback notification method
  fallback: "slack"

# Security
security:
  # Verify webhook signatures
  verify_signatures: true
  
  # Use HTTPS only
  require_https: true
  
  # Validate payload
  validate_payload: true
  
  # Encrypt sensitive data
  encrypt_sensitive: true

# Email Specific Settings
email_settings:
  # HTML email support
  html_enabled: true
  
  # Plain text fallback
  plain_text_fallback: true
  
  # Email headers
  headers:
    X-Mailer: "REChain VC Lab GitHub Integration"
    X-Priority: "3"
    
  # Email formatting
  formatting:
    # Use HTML tables for structured data
    use_tables: true
    
    # Include GitHub avatars
    include_avatars: true
    
    # Use GitHub styling
    use_github_styling: true
    
  # Unsubscribe functionality
  unsubscribe:
    enabled: true
    footer_text: "To unsubscribe from these notifications, reply with 'UNSUBSCRIBE'"
    
  # Email archiving
  archiving:
    enabled: true
    archive_address: "archive@rechain.vc"
    retention_days: 365
