# Slack Integration Configuration for REChain®️ VC Lab
# This configuration enables Slack notifications for GitHub events

name: Slack Integration

# Slack App Configuration
slack:
  # Bot token (store in GitHub Secrets as SLACK_BOT_TOKEN)
  bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
  
  # Channel configurations
  channels:
    # General notifications
    general: "#rechain-vc-lab"
    
    # Development notifications
    development: "#rechain-dev"
    
    # Release notifications
    releases: "#rechain-releases"
    
    # Security notifications
    security: "#rechain-security"
    
    # CI/CD notifications
    ci: "#rechain-ci"

# Notification Settings
notifications:
  # Issue events
  issues:
    created: true
    closed: true
    assigned: true
    labeled: true
    commented: true
    
  # Pull request events
  pull_requests:
    opened: true
    closed: true
    merged: true
    reviewed: true
    commented: true
    
  # Release events
  releases:
    published: true
    prereleased: true
    
  # Workflow events
  workflows:
    success: true
    failure: true
    cancelled: true
    
  # Security events
  security:
    vulnerability: true
    dependency: true
    secret: true

# Message Templates
templates:
  issue_created: |
    🐛 New Issue: <{url}|{title}>
    Repository: {repository}
    Author: {author}
    Labels: {labels}
    
  issue_closed: |
    ✅ Issue Closed: <{url}|{title}>
    Repository: {repository}
    Closed by: {closed_by}
    
  pr_opened: |
    🔄 New Pull Request: <{url}|{title}>
    Repository: {repository}
    Author: {author}
    Base: {base} ← Head: {head}
    
  pr_merged: |
    🎉 Pull Request Merged: <{url}|{title}>
    Repository: {repository}
    Merged by: {merged_by}
    
  release_published: |
    🚀 New Release: <{url}|{name}>
    Repository: {repository}
    Tag: {tag}
    Author: {author}
    
  workflow_success: |
    ✅ Workflow Success: {workflow}
    Repository: {repository}
    Branch: {branch}
    Commit: {commit}
    
  workflow_failure: |
    ❌ Workflow Failed: {workflow}
    Repository: {repository}
    Branch: {branch}
    Commit: {commit}
    <{url}|View Details>

# Custom Fields
custom_fields:
  # Add custom fields for your organization
  project: "REChain VC Lab"
  team: "Development Team"
  environment: "Production"

# Filtering Rules
filters:
  # Only notify for specific branches
  branches:
    include: ["main", "develop", "release/*"]
    exclude: ["feature/*", "bugfix/*"]
    
  # Only notify for specific labels
  labels:
    include: ["bug", "feature", "security", "release"]
    exclude: ["documentation", "chore"]
    
  # Only notify for specific repositories
  repositories:
    include: ["rechain-vc-lab", "rechain-*"]
    exclude: ["test-*", "temp-*"]

# Rate Limiting
rate_limiting:
  # Maximum notifications per hour
  max_per_hour: 50
  
  # Cooldown period between notifications
  cooldown_seconds: 30
  
  # Batch similar notifications
  batch_similar: true

# Error Handling
error_handling:
  # Retry failed notifications
  retry_attempts: 3
  
  # Retry delay in seconds
  retry_delay: 60
  
  # Log errors to GitHub Actions
  log_errors: true

# Security
security:
  # Verify webhook signatures
  verify_signatures: true
  
  # Use HTTPS only
  require_https: true
  
  # Validate payload
  validate_payload: true
